services:
  http_server:
    user: "0" #root
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      NPM_TOKEN: "${NPM_TOKEN}"
      NODE_ENV: development
    entrypoint:
      - npm
      - run
      - ts:repl
    ports:
      - mode: host
        target: 8080
        published: 38080
        protocol: tcp
      - mode: host
        target: 9229
        published: 39229
        protocol: tcp
    volumes:
      - type: volume
        source: npm_cache
        # npm config get cache
        target: /root/.npm
      - type: bind
        source: .
        target: /app
    working_dir: /app
volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
